[build]
  command = "CI='' npm run build"
  publish = "build"  # Remove leading slash
  base = "/"

[build.environment]
  NODE_VERSION = "18.20.3"
  NPM_VERSION = "10.8.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200